apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-role-migrate-job"
  annotations:
    "helm.sh/hook": post-install
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: main
          image: {{ .Values.image }}
          env:
            - name: PGHOST
              value: {{ .Release.Name }}-svc
            - name: PGPORT
              value: "{{ .Values.containerPort }}"
            - name: PGDATABASE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: POSTGRES_DB
            - name: PGUSER
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: POSTGRES_USER
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: POSTGRES_PASSWORD
            - name: MIGRATE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: MIGRATE_PASSWORD
          command: ["sh", "-c"]
          args:
            - psql --command "
              create role {{ .Values.migrateUserName }} with password '$MIGRATE_PASSWORD' createrole login
              " &&
              echo Non-superuser role "{{ .Values.migrateUserName }}" created in database "$PGDATABASE"
