apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  labels:
    app: {{ .Release.Name }}
spec:
  type: LoadBalancer
  ports:
  - port: {{ .Values.containerPort }}
    nodePort: {{ .Values.localPort }}
    targetPort: {{ .Values.publicPort }}
    protocol: TCP
    name: postgres
  selector:
    app: {{ .Release.Name }}