kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-volume
  labels:
    type: local
    app: {{ .Release.Name }}
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.capacity }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-volume-claim
  labels:
    app: {{ .Release.Name }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.capacity }}